version: '3'

services:
  waymore-postgresdb:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - waymore-postgres-data:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - waymore-network

  waymore_api:
    container_name: waymore_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
    links:
      - waymore-postgresdb
    depends_on:
      - waymore-postgresdb
    volumes:
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./src:/app/src
      - ./db:/app/db
    networks:
      - waymore-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: waymore-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - waymore-postgresdb
    networks:
      - waymore-network

networks:
  waymore-network:
    driver: bridge

volumes:
  waymore-postgres-data:
