export enum DebitReason {
  BET = 'BET',
  TIP = 'TIP',
  BUY_IN = 'BUY_IN',
  WIN = 'WIN',
  PAYOUT = 'PAYOUT',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  CASH_OUT = 'CASH_OUT',
  FREEROUND_WIN = 'FREEROUND_WIN',
  TOURNAMENT_WIN = 'TOURNAMENT_WIN',
  CAMPAIGN_WIN = 'CAMPAIGN_WIN',
  FREEGAME_WIN = 'FREEGAME_WIN',
}
